#ifndef TIPOS_DE_TOKEN
#define TIPOS_DE_TOKEN

#define TOKEN_SEM_TIPO 0
#define PALAVRA_RESERVADA 1
#define CARACTERES_ESPECIAIS 2
#define OPERADORES_COMPOSTOS 3
#define IDENTIFICADORES 4
#define LITERAIS 5

#endif